ConfigFile = '/home/shafiqistaken/.config/lazysql/config.toml'

[application]
DefaultPageSize = 300
DisableSidebar = false
SidebarOverlay = false
MaxQueryHistoryPerConnection = 100

[[database]]
Name = 'bkash-cca-dev'
URL = 'postgres://bkash_read:bkash_read_pass@192.168.13.205:5433/bkash_cca?sslmode=disable'
Provider = 'postgres'
Username = ''
Password = ''
Hostname = ''
Port = ''
DBName = 'bkash_cca'
URLParams = ''
Commands = []

[[database]]
Name = 'zaytoon-fin-admin-dev'
URL = 'postgres://zaytoon_fintech_user:zaytoon_fintech_pass@192.168.13.205:5433/zaytoon_fin_admin?sslmode=disable'
Provider = 'postgres'
Username = ''
Password = ''
Hostname = ''
Port = ''
DBName = 'zaytoon_fin_admin'
URLParams = ''
Commands = []

[[database]]
Name = 'zaytoon-onboarding-dev'
URL = 'postgresql://zaytoon_fintech_user:zaytoon_fintech_pass@192.168.13.205:5433/zaytoon_fin_applications?sslmode=disable'
Provider = 'postgres'
Username = ''
Password = ''
Hostname = ''
Port = ''
DBName = 'zaytoon_fin_applications'
URLParams = ''
Commands = []

[[database]]
Name = 'berger-dev'
URL = 'mysql://berger_user:berger_pass@192.168.13.25:6033/berger_360'
Provider = 'mysql'
Username = ''
Password = ''
Hostname = ''
Port = ''
DBName = 'berger_360'
URLParams = ''
Commands = []
