ConfigFile = '/home/shafiqistaken/.config/lazysql/config.toml'

[application]
DefaultPageSize = 300
DisableSidebar = false
SidebarOverlay = false
MaxQueryHistoryPerConnection = 100

[[database]]
Name = 'bkash-cca-dev'
URL = 'mysql://bkash-cca-user:bkash@cca!password@192.168.13.43:6033/bkash_cca_core'
Provider = 'mysql'
Username = ''
Password = ''
Hostname = ''
Port = ''
DBName = 'bkash_cca_core'
URLParams = ''
Commands = []

[[database]]
Name = 'demo-cca-dev'
URL = 'mysql://bkash-cca-user:bkash@cca!password@192.168.13.43:6033/demo_cca_core'
Provider = 'mysql'
Username = ''
Password = ''
Hostname = ''
Port = ''
DBName = 'demo_cca_core'
URLParams = ''
Commands = []

[[database]]
Name = 'zaytoon-fin-admin-dev'
URL = 'postgres://zaytoon_fintech_user:zaytoon_fintech_pass@192.168.13.205:5433/zaytoon_fin_admin?sslmode=disable'
Provider = 'postgres'
Username = ''
Password = ''
Hostname = ''
Port = ''
DBName = 'zaytoon_fin_admin'
URLParams = ''
Commands = []

[[database]]
Name = 'zaytoon-onboarding-dev'
URL = 'postgresql://zaytoon_fintech_user:zaytoon_fintech_pass@192.168.13.205:5433/zaytoon_fin_applications?sslmode=disable'
Provider = 'postgres'
Username = ''
Password = ''
Hostname = ''
Port = ''
DBName = 'zaytoon_fin_applications'
URLParams = ''
Commands = []

[[database]]
Name = 'berger-dev'
URL = 'mysql://berger_user:berger_pass@192.168.13.25:6033/berger_360'
Provider = 'mysql'
Username = ''
Password = ''
Hostname = ''
Port = ''
DBName = 'berger_360'
URLParams = ''
Commands = []

[[database]]
Name = 'agenthive-local'
URL = 'mysql://agenthive_user:agenthive_pass@0.0.0.0:10030/agenthive_db'
Provider = 'mysql'
Username = ''
Password = ''
Hostname = ''
Port = ''
DBName = 'agenthive_db'
URLParams = ''
Commands = []
