# Application bindings
bindd = SUPER, RETURN, Terminal, exec, uwsm-app -- xdg-terminal-exec --dir="$(omarchy-cmd-terminal-cwd)"
bindd = SUPER SHIFT, RETURN, Terminal, exec, uwsm-app -- warp-terminal
bindd = SUPER SHIFT, F, File manager, exec, uwsm-app -- xdg-terminal-exec -e yazi
bindd = SUPER SHIFT, B, Browser, exec, omarchy-launch-browser
bindd = SUPER SHIFT ALT, B, Browser (private), exec, omarchy-launch-browser --private
# bindd = SUPER SHIFT, M, Music, exec, omarchy-launch-or-focus spotify
bindd = SUPER SHIFT, N, NeoVim, exec, omarchy-launch-editor
bindd = SUPER SHIFT, C, CodeOSS, exec, code
# bindd = SUPER SHIFT, T, Activity, exec, omarchy-launch-tui btop
bindd = SUPER SHIFT, A, Activity, exec, omarchy-launch-or-focus-tui btop
bindd = SUPER SHIFT, T, Telegram, exec, omarchy-launch-or-focus-tui ~/.cargo/bin/tgt
bindd = SUPER SHIFT, K, Kubernetes, exec, omarchy-launch-or-focus-tui k9s
bindd = SUPER SHIFT, D, Docker, exec, omarchy-launch-or-focus-tui lazydocker
# bindd = SUPER SHIFT, P, Posting, exec, uwsm-app -- xdg-terminal-exec -e posting --collection ~/projects/playground/posting
bindd = SUPER SHIFT, P, Posting, exec, omarchy-launch-or-focus-tui posting --collection ~/projects/playground/posting
bindd = SUPER SHIFT, S, Database, exec, omarchy-launch-or-focus-tui lazysql 
# bindd = SUPER SHIFT, G, Signal, exec, omarchy-launch-or-focus ^signal$ "uwsm-app -- signal-desktop"
# bindd = SUPER SHIFT, O, Obsidian, exec, omarchy-launch-or-focus ^obsidian$ "uwsm-app -- obsidian -disable-gpu --enable-wayland-ime"
# bindd = SUPER SHIFT, W, Typora, exec, uwsm-app -- typora --enable-wayland-ime

# If your web app url contains #, type it as ## to prevent hyprland treating it as a comment
# bindd = SUPER SHIFT, A, ChatGPT, exec, omarchy-launch-webapp "https://chatgpt.com"
# bindd = SUPER SHIFT ALT, A, Grok, exec, omarchy-launch-webapp "https://grok.com"
bindd = SUPER SHIFT ALT, A, ChatGPT, exec, omarchy-launch-webapp "https://chatgpt.com"
bindd = SUPER SHIFT, Y, YouTube, exec, omarchy-launch-or-focus-tui ~/.cargo/bin/youtube-tui
bindd = SUPER SHIFT ALT, G, WhatsApp, exec, omarchy-launch-or-focus-webapp WhatsApp "https://web.whatsapp.com/"
# bindd = SUPER SHIFT CTRL, G, Google Messages, exec, omarchy-launch-or-focus-webapp "Google Messages" "https://messages.google.com/web/conversations"
# bindd = SUPER SHIFT, P, Google Photos, exec, omarchy-launch-or-focus-webapp "Google Photos" "https://photos.google.com/"

# Overwrite existing bindings, like putting Omarchy Menu on Super + Space
# unbind = SUPER, SPACE
# bindd = SUPER, SPACE, Omarchy menu, exec, omarchy-menu
