windowrule = workspace 1, match:class org.omarchy.btop
windowrule = tag -floating-window, match:class org.omarchy.btop

windowrule = workspace 2, match:tag terminal

windowrule = tag +ide, match:class code-oss
windowrule = workspace 3, match:tag ide

windowrule = tag +browser, match:class firefox-developer-edition
windowrule = tag +browser, match:class brave-browser
windowrule = workspace 4, match:tag browser

windowrule = workspace 5, match:class org.omarchy.lazysql
windowrule = workspace 6, match:class org.omarchy.lazydocker
windowrule = workspace 6, match:class org.omarchy.k9s
windowrule = workspace 7, match:class org.omarchy.posting
windowrule = workspace 8, match:class org.omarchy.tgt
windowrule = workspace 9, match:class org.omarchy.youtube-tui
