alias srcbrc="source ~/.bashrc"
alias ocat='cat'
alias cat='bat --paging=never'
alias hg="history | grep"
alias cal3="cal -3 -s"

# Git aliases. g='git' comes from omarchy...
alias gi='git init'
alias gcl='git clone'
alias gpl='git pull'
alias gps='git push'
alias gs='git status'
alias ga='git add .'
alias gc='git cz'
alias gac='git add . && git cz'
alias gcns='SUGGESTION=false git cz'
alias gacns='git add . && SUGGESTION=false git cz'
alias gaca='git add . && git commit --amend --no-edit'
alias grf='git rm -rf --cached'
alias gco='git checkout'
alias gcom='git checkout main'
alias gcod='git checkout development'
alias gb='git branch'
alias gr='git remote'
alias grso='git remote set-url origin'
alias grao='git remote add origin'
alias gl='git log'
alias gl1='git log -1'
alias glg='git log --graph --oneline --decorate --all'
alias gm='git merge'
alias grh='git reset --hard'

# Docker aliases. d='docker' comes from omarchy...
alias dps='docker ps -a'
alias dps='docker ps'
alias dpa='docker ps -a'
alias dstop='docker stop'
alias drm='docker rm'
alias drmf='docker rm -f'
alias dd='docker rm -f'
alias drmi='docker rmi'
alias dim='docker images'
alias drmiall='docker rmi $(docker images -q)'
alias dex='docker exec -it'
alias dlog='docker logs -f'
alias dbuild='docker build -t'
alias drun='docker run -it --rm'
alias dclean='docker system prune -af --volumes'
alias dvls='docker volume ls'
alias dvrm='docker volume rm'

# Docker compose
alias dc='docker compose'
alias dcu='docker compose up -d'
alias dcd='docker compose down'
alias dclog='docker compose logs -f'
alias dcb='docker compose build'
alias dcr='docker compose run --rm'
alias dcex='docker compose exec'
alias dcps='docker compose ps'

# kubectl
alias k='kubectl'
alias kp='kubectl get pods'
alias kpw='watch kubectl get pods'
alias kd='kubectl get deployments'
alias ks='kubectl get svc'
alias kn='kubectl get nodes'
alias ksec='kubectl get secrets'
alias kgp='kubectl get pods'
alias kgd='kubectl get deployments'
alias kgs='kubectl get svc'
alias kgn='kubectl get nodes'
alias kgsec='kubectl get secrets'
alias kdp='kubectl describe pod'
alias kds='kubectl describe svc'
alias kctx='kubectl config use-context'
alias kns='kubectl config set-context --current --namespace'
alias kl='kubectl logs -f'
alias kex='kubectl exec -it'
alias ka='kubectl apply -f'
alias kdel='kubectl delete -f'
alias kpf='kubectl port-forward'
alias kr='kubectl rollout restart'
alias kvsec='kubectl view-secret' # kubectl krew install view-secret

# NPM shortcuts
alias ni='npm install'
alias nid='npm install --save-dev'
alias nig='npm install -g'
alias nr='npm run'
alias nrs='npm run start'
alias nrd='npm run dev'
alias nrt='npm run test'
alias nrl='npm run lint'
alias nrb='npm run build'
alias nu='npm update'
alias nci='npm ci'
alias nlu='npm list -g --depth=0'
alias np='npm publish'
alias npp='npm publish --access public'
alias nun='npm uninstall'

# Spring Boot shortcuts
alias sbr='./mvnw spring-boot:run'
alias sbb='./mvnw clean package'
alias sbt='./mvnw test'
alias sbc='./mvnw clean'
alias sbcr='./mvnw clean && ./mvnw spring-boot:run'
alias sbi='./mvnw install'

# Flutter shortcuts
alias f='fvm flutter'
alias fr='fvm flutter run'
alias fb='fvm flutter build'
alias ft='fvm flutter test'
alias fa='fvm flutter analyze'
alias fc='fvm flutter clean'
alias fp='fvm flutter pub get'
alias fpu='fvm flutter pub upgrade'
alias fpl='fvm flutter pub outdated'
alias fpp='fvm flutter pub publish'
alias fpc='fvm flutter pub cache'
alias fpcu='fvm flutter pub cache repair'
alias fpccl='fvm flutter pub cache clear'
alias fpcclu='fvm flutter pub cache clear --dry-run'

# Python shortcuts
alias p='python'
