# alias p='python'

alias cat='bat --paging=never'

# Git aliases. g='git' comes from omarchy...
alias gpl='g pull'
alias gps='g push'
alias gs='g status'
alias ga='g add .'
alias gc='ga && g cz'
alias gco='g checkout'
alias gb='g branch'
alias gl='g log'
alias gl1='gl -1'
alias gm='g merge'

# Docker aliases. d='docker' comes from omarchy...
alias dps='d ps -a'
alias dps='d ps'
alias dpa='dps -a'
alias dstop='d stop'
alias drm='d rm'
alias drmf='d rm -f'
alias dd='d rm -f'
alias drmi='d rmi'
alias dim='d images'
alias drmiall='drmi $(dim -q)'
alias dex='d exec -it'
alias dlog='d logs -f'
alias dbuild='d build -t'
alias drun='d run -it --rm'
alias dclean='d system prune -af --volumes'
alias dvls='d volume ls'
alias dvrm='d volume rm'

# Docker compose
alias dc='d compose'
alias dcu='dc up -d'
alias dcd='dc down'
alias dclog='dc logs -f'
alias dcb='dc build'
alias dcr='dc run --rm'
alias dcex='dc exec'
alias dcps='dc ps'

# kubectl
alias k='kubectl'
alias kp='k get pods'
alias ks='k get svc'
alias kn='k get nodes'
alias kdp='k describe pod'
alias kds='k describe svc'
alias kctx='k config use-context'
alias kns='k config set-context --current --namespace'
alias kl='k logs -f'
alias kex='k exec -it'
alias kap='k apply -f'
alias kdel='k delete -f'

# NPM shortcuts
alias ni='npm install'
alias nid='ni --save-dev'
alias nig='ni -g'
alias nr='npm run'
alias nrs='nr start'
alias nrd='nr dev'
alias nrt='nr test'
alias nrl='nr lint'
alias nrb='nr build'
alias nu='npm update'
alias nci='npm ci'
alias nlu='npm list -g --depth=0'
alias np='npm publish --access public'
alias nun='npm uninstall'

# Spring Boot shortcuts
alias sbr='./mvnw spring-boot:run'
alias sbb='./mvnw clean package'
alias sbt='./mvnw test'
alias sbc='./mvnw clean'
alias sbcr='sb-c && sb-r'
alias sbi='./mvnw install'